# Generated with ./gen_packages_map.sh > packages_map.py
# for driver version 19.50-967956

packages_map = {
    'amdgpu':                                None,                            #unneeded_open_component
    'amdgpu-core':                           'amdgpu-core-meta',              #mapped_manually
    'amdgpu-dkms':                           None,                            #unneeded_open_component
    'amdgpu-doc':                            None,                            #arch_specific_instructions_will_be_covered_in_archwiki
    'amdgpu-hwe':                            None,                            #unneeded_open_component
    'amdgpu-lib':                            None,                            #unneeded_open_component
    'amdgpu-lib-hwe':                        None,                            #unneeded_open_component
    'amdgpu-lib32':                          None,                            #unneeded_open_component
    'amdgpu-pro':                            None,                            #disabled_because_hwe_version_is_available
    'amdgpu-pro-core':                       'amdgpu-pro-core-meta',          #mapped_manually
    'amdgpu-pro-hwe':                        None,                            #we_have_already_combined_libgl_to_single_package
    'amdgpu-pro-lib32':                      None,                            #we_have_already_combined_libgl_to_single_package
    'amdgpu-pro-pin':                        None,                            #debian_specific_package,_not_needed
    'amf-amdgpu-pro':                        'amf-amdgpu-pro',                #
    'clinfo-amdgpu-pro':                     None,                            #unneeded_pro_component
    'clinfo-amdgpu-pro:i386':                None,                            #unneeded_pro_component
    'glamor-amdgpu':                         None,                            #unneeded_open_component
    'glamor-amdgpu-dev':                     None,                            #unneeded_open_component
    'gst-omx-amdgpu':                        None,                            #unneeded_open_component
    'gst-omx-amdgpu:i386':                   None,                            #unneeded_open_component
    'hip-amdgpu-pro':                        'hip-amdgpu-pro',                #
    'hsakmt-roct-amdgpu':                    'hsakmt-roct-amdgpu',            #
    'hsakmt-roct-amdgpu-dev':                'hsakmt-roct-amdgpu-dev',        #
    'libdrm-amdgpu-amdgpu1':                 None,                            #unneeded_open_component
    'libdrm-amdgpu-amdgpu1:i386':            None,                            #unneeded_open_component
    'libdrm-amdgpu-common':                  None,                            #unneeded_open_component
    'libdrm-amdgpu-dev':                     None,                            #not_installed_even_in_ubuntu
    'libdrm-amdgpu-dev:i386':                None,                            #not_installed_even_in_ubuntu
    'libdrm-amdgpu-radeon1':                 None,                            #not_installed_even_in_ubuntu
    'libdrm-amdgpu-radeon1:i386':            None,                            #not_installed_even_in_ubuntu
    'libdrm-amdgpu-utils':                   None,                            #not_installed_even_in_ubuntu
    'libdrm-amdgpu-utils:i386':              None,                            #not_installed_even_in_ubuntu
    'libdrm2-amdgpu':                        None,                            #unneeded_open_component
    'libdrm2-amdgpu:i386':                   None,                            #unneeded_open_component
    'libegl1-amdgpu-mesa':                   None,                            #unneeded_open_component
    'libegl1-amdgpu-mesa:i386':              None,                            #unneeded_open_component
    'libegl1-amdgpu-mesa-dev':               None,                            #unneeded_open_component
    'libegl1-amdgpu-mesa-dev:i386':          None,                            #unneeded_open_component
    'libegl1-amdgpu-mesa-drivers':           None,                            #unneeded_open_component
    'libegl1-amdgpu-mesa-drivers:i386':      None,                            #unneeded_open_component
    'libegl1-amdgpu-pro':                    'amdgpu-pro-libgl',              #mapped_manually
    'libegl1-amdgpu-pro:i386':               'lib32-amdgpu-pro-libgl',        #mapped_manually
    'libgbm-amdgpu-dev':                     None,                            #unneeded_open_component
    'libgbm-amdgpu-dev:i386':                None,                            #unneeded_open_component
    'libgbm1-amdgpu':                        None,                            #unneeded_open_component
    'libgbm1-amdgpu:i386':                   None,                            #unneeded_open_component
    'libgl1-amdgpu-mesa-dev':                None,                            #unneeded_open_component
    'libgl1-amdgpu-mesa-dev:i386':           None,                            #unneeded_open_component
    'libgl1-amdgpu-mesa-dri':                None,                            #unneeded_open_component
    'libgl1-amdgpu-mesa-dri:i386':           None,                            #unneeded_open_component
    'libgl1-amdgpu-mesa-glx':                None,                            #unneeded_open_component
    'libgl1-amdgpu-mesa-glx:i386':           None,                            #unneeded_open_component
    'libgl1-amdgpu-pro-appprofiles':         'amdgpu-pro-libgl',              #mapped_manually
    'libgl1-amdgpu-pro-dri':                 'amdgpu-pro-libgl',              #mapped_manually
    'libgl1-amdgpu-pro-dri:i386':            'lib32-amdgpu-pro-libgl',        #mapped_manually
    'libgl1-amdgpu-pro-ext':                 None,                            #disabled_because_hwe_version_is_available
    'libgl1-amdgpu-pro-ext:i386':            None,                            #disabled_because_hwe_version_is_available
    'libgl1-amdgpu-pro-ext-hwe':             'amdgpu-pro-libgl',              #mapped_manually
    'libgl1-amdgpu-pro-ext-hwe:i386':        'lib32-amdgpu-pro-libgl',        #mapped_manually
    'libgl1-amdgpu-pro-glx':                 'amdgpu-pro-libgl',              #mapped_manually
    'libgl1-amdgpu-pro-glx:i386':            'lib32-amdgpu-pro-libgl',        #mapped_manually
    'libglapi-amdgpu-mesa':                  None,                            #unneeded_open_component
    'libglapi-amdgpu-mesa:i386':             None,                            #unneeded_open_component
    'libglapi1-amdgpu-pro':                  'amdgpu-pro-libgl',              #mapped_manually
    'libglapi1-amdgpu-pro:i386':             'lib32-amdgpu-pro-libgl',        #mapped_manually
    'libgles1-amdgpu-mesa':                  None,                            #unneeded_open_component
    'libgles1-amdgpu-mesa:i386':             None,                            #unneeded_open_component
    'libgles1-amdgpu-mesa-dev':              None,                            #unneeded_open_component
    'libgles1-amdgpu-mesa-dev:i386':         None,                            #unneeded_open_component
    'libgles2-amdgpu-mesa':                  None,                            #unneeded_open_component
    'libgles2-amdgpu-mesa:i386':             None,                            #unneeded_open_component
    'libgles2-amdgpu-mesa-dev':              None,                            #unneeded_open_component
    'libgles2-amdgpu-mesa-dev:i386':         None,                            #unneeded_open_component
    'libgles2-amdgpu-pro':                   'amdgpu-pro-libgl',              #mapped_manually
    'libgles2-amdgpu-pro:i386':              'lib32-amdgpu-pro-libgl',        #mapped_manually
    'libllvm9.0-amdgpu':                     None,                            #unneeded_open_component
    'libllvm9.0-amdgpu:i386':                None,                            #unneeded_open_component
    'libopencl1-amdgpu-pro':                 None,                            #unneeded_pro_component
    'libopencl1-amdgpu-pro:i386':            None,                            #unneeded_pro_component
    'libosmesa6-amdgpu':                     None,                            #unneeded_open_component
    'libosmesa6-amdgpu:i386':                None,                            #unneeded_open_component
    'libosmesa6-amdgpu-dev':                 None,                            #unneeded_open_component
    'libosmesa6-amdgpu-dev:i386':            None,                            #unneeded_open_component
    'libwayland-amdgpu-client0':             None,                            #installed_in_ubuntu_but_probably_not_needed
    'libwayland-amdgpu-client0:i386':        None,                            #installed_in_ubuntu_but_probably_not_needed
    'libwayland-amdgpu-cursor0':             None,                            #not_installed_even_in_ubuntu
    'libwayland-amdgpu-cursor0:i386':        None,                            #not_installed_even_in_ubuntu
    'libwayland-amdgpu-dev':                 None,                            #not_installed_even_in_ubuntu
    'libwayland-amdgpu-dev:i386':            None,                            #not_installed_even_in_ubuntu
    'libwayland-amdgpu-doc':                 None,                            #not_installed_even_in_ubuntu
    'libwayland-amdgpu-egl1':                None,                            #unneeded_open_component
    'libwayland-amdgpu-egl1:i386':           None,                            #unneeded_open_component
    'libwayland-amdgpu-server0':             None,                            #installed_in_ubuntu_but_probably_not_needed
    'libwayland-amdgpu-server0:i386':        None,                            #installed_in_ubuntu_but_probably_not_needed
    'libxatracker-amdgpu-dev':               None,                            #not_installed_even_in_ubuntu
    'libxatracker-amdgpu-dev:i386':          None,                            #not_installed_even_in_ubuntu
    'libxatracker2-amdgpu':                  None,                            #unneeded_open_component
    'libxatracker2-amdgpu:i386':             None,                            #unneeded_open_component
    'llvm-amdgpu':                           None,                            #not_installed_even_in_ubuntu
    'llvm-amdgpu:i386':                      None,                            #not_installed_even_in_ubuntu
    'llvm-amdgpu-9.0':                       None,                            #not_installed_even_in_ubuntu
    'llvm-amdgpu-9.0:i386':                  None,                            #not_installed_even_in_ubuntu
    'llvm-amdgpu-9.0-dev':                   None,                            #not_installed_even_in_ubuntu
    'llvm-amdgpu-9.0-dev:i386':              None,                            #not_installed_even_in_ubuntu
    'llvm-amdgpu-9.0-runtime':               None,                            #not_installed_even_in_ubuntu
    'llvm-amdgpu-9.0-runtime:i386':          None,                            #not_installed_even_in_ubuntu
    'llvm-amdgpu-dev':                       None,                            #not_installed_even_in_ubuntu
    'llvm-amdgpu-dev:i386':                  None,                            #not_installed_even_in_ubuntu
    'llvm-amdgpu-runtime':                   None,                            #not_installed_even_in_ubuntu
    'llvm-amdgpu-runtime:i386':              None,                            #not_installed_even_in_ubuntu
    'mesa-amdgpu-common-dev':                None,                            #not_installed_even_in_ubuntu
    'mesa-amdgpu-common-dev:i386':           None,                            #not_installed_even_in_ubuntu
    'mesa-amdgpu-omx-drivers':               None,                            #unneeded_open_component
    'mesa-amdgpu-omx-drivers:i386':          None,                            #unneeded_open_component
    'mesa-amdgpu-va-drivers':                None,                            #unneeded_open_component
    'mesa-amdgpu-va-drivers:i386':           None,                            #unneeded_open_component
    'mesa-amdgpu-vdpau-drivers':             None,                            #unneeded_open_component
    'mesa-amdgpu-vdpau-drivers:i386':        None,                            #unneeded_open_component
    'opencl-amdgpu-pro':                     None,                            #its_dependencies_go_directly_to_amf-amdgpu-pro
    'opencl-amdgpu-pro-comgr':               'opencl-amdgpu-pro-comgr',       #
    'opencl-amdgpu-pro-dev':                 'opencl-amdgpu-pro-dev',         #
    'opencl-amdgpu-pro-icd':                 'opencl-amdgpu-pro-pal',         #mapped_manually
    'opencl-orca-amdgpu-pro-icd':            'opencl-amdgpu-pro-orca',        #mapped_manually
    'opencl-orca-amdgpu-pro-icd:i386':       'lib32-opencl-amdgpu-pro-orca',  #mapped_manually
    'vulkan-amdgpu':                         None,                            #unneeded_open_component
    'vulkan-amdgpu:i386':                    None,                            #unneeded_open_component
    'vulkan-amdgpu-pro':                     'vulkan-amdgpu-pro',             #
    'vulkan-amdgpu-pro:i386':                'lib32-vulkan-amdgpu-pro',       #
    'wayland-protocols-amdgpu':              None,                            #not_installed_even_in_ubuntu
    'xserver-xorg-amdgpu-video-amdgpu':      None,                            #unneeded_open_component
    'xserver-xorg-hwe-amdgpu-video-amdgpu':  None,                            #unneeded_open_component
}
