# Author: Janusz Lewandowski <lew21@xtreeme.org>
# Maintainer: David McFarland <corngood@gmail.com>
# Autogenerated from AMD's Packages file

pkgbase=amdgpu-pro-installer
pkgname=(amdgpu-pro amdgpu-pro-dkms amdgpu-pro-firmware amdgpu-pro-libdrm amdgpu-pro-libgl amdgpu-pro-opencl amdgpu-pro-vdpau amdgpu-pro-vulkan lib32-amdgpu-pro lib32-amdgpu-pro-libdrm lib32-amdgpu-pro-libgl lib32-amdgpu-pro-opencl lib32-amdgpu-pro-vdpau lib32-amdgpu-pro-vulkan xf86-video-amdgpu-pro)
pkgver=16.30.3.315407
pkgrel=2
arch=('x86_64')
url='http://www.amd.com'
license=('custom:AMD')
makedepends=('wget')

DLAGENTS='https::/usr/bin/wget --referer http://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Beta-Driver-for-Vulkan-Release-Notes.aspx -N %u'
PKGEXT='.pkg.tar'

source=(https://www2.ati.com/drivers/linux/amdgpu-pro_16.30.3-315407.tar.xz
	0001-add-OS-detection-for-arch.patch
	0002-update-kcl_ttm_bo_reserve-for-linux-4.7.patch
	0003-add-kcl_drm_gem_object_lookup.patch
	0004-paging-changes-for-linux-4.6.patch
	0005-LRU-stuff-isn-t-available-until-4.7.x.patch
	0006-Change-name-of-vblank_disable_allowed-to-vblank_disa.patch
	0007-Remove-connector-parameter-from-__drm_atomic_helper_.patch
	0008-fix-apparent-typo-in-bandwidth_calcs-causing-array-e.patch
	0009-disable-dal-by-default.patch
	0010-remove-dependency-on-System.map.patch)
sha256sums=(97d6fb64617cf2cefe780e5fb83b29d8ee4e3e7886b71fe3d92b0113847b2354
	ae5fed04cd626aadff6d4c7c59657f52a8dd6be3df4a9686702e74aa8c72d1de
	df36d1d9f470094432b765016b558624fa9b28355c82a722f7bd4facdf912ce2
	4afabc203dc52a8ad15f1d4dc62887d1a11472f11c1aa9f9adb8affc183f297b
	0a0657826270a963be76f9e3a882432df4f6ac0628dd0966289cc5c064cadeb6
	fe0075575bae0a7f76daa0686ab23464b867ef8ed0b4d39cec4bd566ec39f99c
	a0e94234555f5254df096a93e050edbc341603d0b1d527f7b0c3179e111b7be1
	2e291935e35ecdc9f7c87d288db9d73a27f4f5cc3b08f95b8b39fef3934c6735
	50c56c4e2ed55d66e5d5e5689b2f146de63dbb3edc2bafabf5ca98e8ae58e028
	7e5640468e9ede54a8b3cc8fd67d6c3ae3738aec959a655c9aeaac9570a646f9
	2f6c74a5a909f27a5a18eae5acf2ca90c99c4f2e4aa8ceb766dbf8a0cb431817)



# extracts a debian package
# $1: deb file to extract
extract_deb() {
	local tmpdir="$(basename "${1%.deb}")"
	rm -Rf "$tmpdir"
	mkdir "$tmpdir"
	cd "$tmpdir"
	ar x "$1"
	tar -C "${pkgdir}" -xf data.tar.xz
}
# move ubuntu specific /usr/lib/x86_64-linux-gnu to /usr/lib
# $1: library dir
# $2: destination (optional)
move_libdir() {
	local libdir="usr/lib"
	if [ -n "$2" ]; then
		libdir="$2"
	fi
	if [ -d "$1" ]; then
		if [ -d "${pkgdir}/${libdir}" ]; then
			cp -ar -t "${pkgdir}/${libdir}/" "$1"/*
			rm -rf "$1"
		else
			mkdir -p "${pkgdir}/${libdir}"
			mv -t "${pkgdir}/${libdir}/" "$1"/*
			rmdir "$1"
		fi
	fi
}


package_amdgpu-pro () {
	pkgdesc="The AMDGPU Pro driver package"
	install=amdgpu-pro-core.install
	arch=('x86_64')
	depends=('libxxf86vm' 'libxshmfence' 'libx11' 'xf86-video-amdgpu-pro=16.30.3-315407' 'libxext' 'libxcb>=1.9.2' 'libxfixes' 'libxcb>=1.8' 'libx11>=1.4.99.1' 'linux-firmware' 'libxdamage>=1.1' 'libxcb')

	extract_deb "${srcdir}"/amdgpu-pro-driver/./amdgpu-pro_16.30.3-315407_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./amdgpu-pro-core_16.30.3-315407_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./amdgpu-pro-graphics_16.30.3-315407_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libegl1-amdgpu-pro_16.30.3-315407_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libegl1-amdgpu-pro-dev_16.30.3-315407_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libgbm1-amdgpu-pro_16.30.3-315407_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libgl1-amdgpu-pro-dev_16.30.3-315407_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libgl1-amdgpu-pro-dri_16.30.3-315407_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libgl1-amdgpu-pro-glx_16.30.3-315407_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libgles2-amdgpu-pro_16.30.3-315407_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libgles2-amdgpu-pro-dev_16.30.3-315407_amd64.deb
	move_libdir "${pkgdir}/usr/lib/x86_64-linux-gnu"
	move_libdir "${pkgdir}/lib"

	# extra_commands:
	sed -i 's@/usr/lib/x86_64-linux-gnu/@/usr/lib/@' ${pkgdir}/usr/lib/amdgpu-pro/ld.conf
	sed -i 's@/usr/lib/i386-linux-gnu/@/usr/lib32/@' ${pkgdir}/usr/lib/amdgpu-pro/ld.conf
	mkdir -p ${pkgdir}/etc/ld.so.conf.d/
	ln -s /usr/lib/amdgpu-pro/ld.conf ${pkgdir}/etc/ld.so.conf.d/10-amdgpu-pro.conf
	mkdir -p ${pkgdir}/etc/modprobe.d/
	ln -s /usr/lib/amdgpu-pro/modprobe.conf ${pkgdir}/etc/modprobe.d/amdgpu-pro.conf
}


package_amdgpu-pro-dkms () {
	pkgdesc="amdgpu-pro driver in DKMS format."
	arch=('any')
	depends=('dkms>=1.95')

	extract_deb "${srcdir}"/amdgpu-pro-driver/./amdgpu-pro-dkms_16.30.3-315407_all.deb
	move_libdir "${pkgdir}/usr/lib/x86_64-linux-gnu"
	move_libdir "${pkgdir}/lib"

	# extra_commands:
	(cd ${pkgdir}/usr/src/amdgpu-pro-16.30.3-315407;
		sed -i 's/\/extra/\/extramodules/' dkms.conf
			patch -p1 -i "${srcdir}/0001-add-OS-detection-for-arch.patch";
		patch -p1 -i "${srcdir}/0002-update-kcl_ttm_bo_reserve-for-linux-4.7.patch";
		patch -p1 -i "${srcdir}/0003-add-kcl_drm_gem_object_lookup.patch";
		patch -p1 -i "${srcdir}/0004-paging-changes-for-linux-4.6.patch";
		patch -p1 -i "${srcdir}/0005-LRU-stuff-isn-t-available-until-4.7.x.patch";
		patch -p1 -i "${srcdir}/0006-Change-name-of-vblank_disable_allowed-to-vblank_disa.patch";
		patch -p1 -i "${srcdir}/0007-Remove-connector-parameter-from-__drm_atomic_helper_.patch";
		patch -p1 -i "${srcdir}/0008-fix-apparent-typo-in-bandwidth_calcs-causing-array-e.patch";
		patch -p1 -i "${srcdir}/0009-disable-dal-by-default.patch";
		patch -p1 -i "${srcdir}/0010-remove-dependency-on-System.map.patch"
	)
}


package_amdgpu-pro-firmware () {
	pkgdesc="The AMDGPU Pro firmware files for amdgpu cards."
	arch=('x86_64')
	extract_deb "${srcdir}"/amdgpu-pro-driver/./amdgpu-pro-firmware_16.30.3-315407_amd64.deb
	move_libdir "${pkgdir}/usr/lib/x86_64-linux-gnu"
	move_libdir "${pkgdir}/lib"

	# extra_commands:
	mv ${pkgdir}/usr/lib/firmware ${pkgdir}/usr/lib/firmware.tmp
	mkdir -p ${pkgdir}/usr/lib/firmware
	mv ${pkgdir}/usr/lib/firmware.tmp ${pkgdir}/usr/lib/firmware/updates
}


package_amdgpu-pro-libdrm () {
	pkgdesc="The AMDGPU Pro userspace interface to kernel DRM services"
	arch=('x86_64')
	depends=()

	extract_deb "${srcdir}"/amdgpu-pro-driver/./libdrm-amdgpu-pro-amdgpu1_16.30.3-315407_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libdrm-amdgpu-pro-dev_16.30.3-315407_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libdrm-amdgpu-pro-tools_16.30.3-315407_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libdrm2-amdgpu-pro_16.30.3-315407_amd64.deb
	move_libdir "${pkgdir}/usr/lib/x86_64-linux-gnu"
	move_libdir "${pkgdir}/lib"

}


package_amdgpu-pro-libgl () {
	pkgdesc="The AMDGPU Pro libgl library symlinks"
	arch=('x86_64')
	provides=('libgl')
	conflicts=('libgl')
	depends=(amdgpu-pro)

	move_libdir "${pkgdir}/usr/lib/x86_64-linux-gnu"
	move_libdir "${pkgdir}/lib"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/lib
	cd "${pkgdir}"/usr/lib
	ln -s /usr/lib/amdgpu-pro/libGL.so.1.2   libGL.so.1.2
	ln -s /usr/lib/amdgpu-pro/libEGL.so.1    libEGL.so.1
	ln -s /usr/lib/amdgpu-pro/libGLESv2.so.2 libGLESv2.so.2
	ln -s libGL.so.1.2   libGL.so.1
	ln -s libGL.so.1.2   libGL.so
	ln -s libEGL.so.1    libEGL.so
	ln -s libGLESv2.so   libGLESv2.so
}


package_amdgpu-pro-opencl () {
	pkgdesc="The AMDGPU Pro OpenCL implementation"
	arch=('x86_64')
	provides=('libcl')
	conflicts=('libcl')
	depends=('amdgpu-pro=16.30.3-315407')

	extract_deb "${srcdir}"/amdgpu-pro-driver/./amdgpu-pro-clinfo_16.30.3-315407_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./amdgpu-pro-computing_16.30.3-315407_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./amdgpu-pro-libopencl-dev_16.30.3-315407_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./amdgpu-pro-libopencl1_16.30.3-315407_amd64.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./amdgpu-pro-opencl-icd_16.30.3-315407_amd64.deb
	move_libdir "${pkgdir}/usr/lib/x86_64-linux-gnu"
	move_libdir "${pkgdir}/lib"

}


package_amdgpu-pro-vdpau () {
	pkgdesc="The AMDGPU Pro VDPAU driver"
	arch=('x86_64')
	depends=('libx11' 'amdgpu-pro-libdrm' 'libxcb>=1.8' 'openssl>=1.0.0' 'libdrm>=2.4.31' 'libxcb')

	extract_deb "${srcdir}"/amdgpu-pro-driver/./libvdpau-amdgpu-pro_16.30.3-315407_amd64.deb
	move_libdir "${pkgdir}/usr/lib/x86_64-linux-gnu"
	move_libdir "${pkgdir}/lib"

}


package_amdgpu-pro-vulkan () {
	pkgdesc="The AMDGPU Pro Vulkan driver"
	arch=('x86_64')
	depends=('amdgpu-pro-libdrm')

	extract_deb "${srcdir}"/amdgpu-pro-driver/./amdgpu-pro-vulkan-driver_16.30.3-315407_amd64.deb
	move_libdir "${pkgdir}/usr/lib/x86_64-linux-gnu"
	move_libdir "${pkgdir}/lib"

	# extra_commands:
	sed -i 's@/usr/lib/x86_64-linux-gnu/@/usr/lib/@' ${pkgdir}/etc/vulkan/icd.d/amd_icd64.json
}


package_lib32-amdgpu-pro () {
	pkgdesc="This package contains x86 libs for x86_64 machine usage. (32bit libraries)"
	arch=('x86_64')
	depends=('lib32-libxcb' 'amdgpu-pro-vdpau=16.30.3-315407' 'lib32-libx11>=1.4.99.1' 'lib32-libxcb>=1.9.2' 'amdgpu-pro-opencl=16.30.3-315407' 'lib32-libxcb>=1.8' 'lib32-libxshmfence' 'amdgpu-pro-libdrm' 'lib32-libxfixes' 'amdgpu-pro=16.30.3-315407' 'amdgpu-pro-vulkan=16.30.3-315407' 'lib32-libxext' 'lib32-libx11' 'lib32-libxdamage>=1.1' 'amdgpu-pro' 'lib32-libxxf86vm')

	extract_deb "${srcdir}"/amdgpu-pro-driver/./amdgpu-pro-lib32_16.30.3-315407_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libegl1-amdgpu-pro_16.30.3-315407_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libegl1-amdgpu-pro-dev_16.30.3-315407_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libgbm1-amdgpu-pro_16.30.3-315407_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libgl1-amdgpu-pro-dev_16.30.3-315407_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libgl1-amdgpu-pro-dri_16.30.3-315407_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libgl1-amdgpu-pro-glx_16.30.3-315407_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libgles2-amdgpu-pro_16.30.3-315407_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libgles2-amdgpu-pro-dev_16.30.3-315407_i386.deb
	move_libdir "${pkgdir}/usr/lib/i386-linux-gnu" "usr/lib32"
	move_libdir "${pkgdir}/lib" "usr/lib32"


	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var"

}


package_lib32-amdgpu-pro-libdrm () {
	pkgdesc="The AMDGPU Pro userspace interface to kernel DRM services (32bit libraries)"
	arch=('x86_64')
	depends=('amdgpu-pro-libdrm=16.30.3-315407' 'amdgpu-pro-libdrm')

	extract_deb "${srcdir}"/amdgpu-pro-driver/./libdrm-amdgpu-pro-amdgpu1_16.30.3-315407_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libdrm-amdgpu-pro-dev_16.30.3-315407_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./libdrm2-amdgpu-pro_16.30.3-315407_i386.deb
	move_libdir "${pkgdir}/usr/lib/i386-linux-gnu" "usr/lib32"
	move_libdir "${pkgdir}/lib" "usr/lib32"


	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var"

}


package_lib32-amdgpu-pro-libgl () {
	pkgdesc="The AMDGPU Pro libgl library symlinks (32bit libraries)"
	arch=('x86_64')
	provides=('lib32-libgl')
	conflicts=('lib32-libgl')
	depends=(lib32-amdgpu-pro)

	move_libdir "${pkgdir}/usr/lib/i386-linux-gnu" "usr/lib32"
	move_libdir "${pkgdir}/lib" "usr/lib32"

	# extra_commands:
	mkdir -p "${pkgdir}"/usr/lib32
	cd "${pkgdir}"/usr/lib32
	ln -s /usr/lib32/amdgpu-pro/libGL.so.1.2   libGL.so.1.2
	ln -s /usr/lib32/amdgpu-pro/libEGL.so.1    libEGL.so.1
	ln -s /usr/lib32/amdgpu-pro/libGLESv2.so.2 libGLESv2.so.2
	ln -s libGL.so.1.2   libGL.so.1
	ln -s libGL.so.1.2   libGL.so
	ln -s libEGL.so.1    libEGL.so
	ln -s libGLESv2.so   libGLESv2.so

	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var"

}


package_lib32-amdgpu-pro-opencl () {
	pkgdesc="The AMDGPU Pro OpenCL implementation"
	arch=('x86_64')
	provides=('lib32-libcl')
	conflicts=('lib32-libcl')
	depends=('amdgpu-pro-opencl=16.30.3-315407')

	extract_deb "${srcdir}"/amdgpu-pro-driver/./amdgpu-pro-libopencl-dev_16.30.3-315407_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./amdgpu-pro-libopencl1_16.30.3-315407_i386.deb
	extract_deb "${srcdir}"/amdgpu-pro-driver/./amdgpu-pro-opencl-icd_16.30.3-315407_i386.deb
	move_libdir "${pkgdir}/usr/lib/i386-linux-gnu" "usr/lib32"
	move_libdir "${pkgdir}/lib" "usr/lib32"


	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var"

}


package_lib32-amdgpu-pro-vdpau () {
	pkgdesc="The AMDGPU Pro VDPAU driver (32bit libraries)"
	arch=('x86_64')
	depends=('lib32-libxcb' 'lib32-libxcb>=1.8' 'lib32-zlib>=1.2.0' 'amdgpu-pro-libdrm' 'lib32-openssl>=1.0.0' 'lib32-libx11' 'lib32-libdrm>=2.4.31')

	extract_deb "${srcdir}"/amdgpu-pro-driver/./libvdpau-amdgpu-pro_16.30.3-315407_i386.deb
	move_libdir "${pkgdir}/usr/lib/i386-linux-gnu" "usr/lib32"
	move_libdir "${pkgdir}/lib" "usr/lib32"


	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var"

}


package_lib32-amdgpu-pro-vulkan () {
	pkgdesc="The AMDGPU Pro Vulkan driver (32bit libraries)"
	arch=('x86_64')
	depends=('amdgpu-pro-libdrm')

	extract_deb "${srcdir}"/amdgpu-pro-driver/./amdgpu-pro-vulkan-driver_16.30.3-315407_i386.deb
	move_libdir "${pkgdir}/usr/lib/i386-linux-gnu" "usr/lib32"
	move_libdir "${pkgdir}/lib" "usr/lib32"

	# extra_commands:
	sed -i 's@/usr/lib/i386-linux-gnu/@/usr/lib32/@' ${pkgdir}/etc/vulkan/icd.d/amd_icd32.json

	# lib32 cleanup
	rm -rf "${pkgdir}"/usr/{bin,lib,include,share} "${pkgdir}/var"

}


package_xf86-video-amdgpu-pro () {
	pkgdesc="The AMDGPU Pro X.org video driver"
	arch=('x86_64')
	provides=('xf86-video-amdgpu')
	conflicts=('xf86-video-amdgpu' 'xorg-server<1.18.0' 'X-ABI-VIDEODRV_VERSION<20' 'X-ABI-VIDEODRV_VERSION>=21')
	groups=('xorg-driversxorg')
	depends=('libxxf86vm' 'xorg-server' 'libx11' 'libxext' 'libxfixes' 'libsystemd>=183' 'amdgpu-pro-libdrm' 'libxdamage>=1.1' 'amdgpu-pro' 'libxcb' 'libepoxy>=1.0')

	extract_deb "${srcdir}"/amdgpu-pro-driver/./xserver-xorg-video-amdgpu-pro_16.30.3-315407_amd64.deb
	move_libdir "${pkgdir}/usr/lib/x86_64-linux-gnu"
	move_libdir "${pkgdir}/lib"

	# extra_commands:
	mkdir -p ${pkgdir}/usr/lib/x86_64-linux-gnu
	# This is needed because libglx.so has a hardcoded DRI_DRIVER_PATH
	ln -s /usr/lib/dri ${pkgdir}/usr/lib/x86_64-linux-gnu/dri
	mv ${pkgdir}/usr/lib/amdgpu-pro/1.18/ ${pkgdir}/usr/lib/xorg
	rm -rf ${pkgdir}/usr/lib/amdgpu-pro/1.*
}

