# Author: Janusz Lewandowski <lew21@xtreeme.org>
# Maintainer: David McFarland <corngood@gmail.com>
# Autogenerated from AMD's Packages file

pkgbase=amdgpu-pro-installer
pkgname=(lib32-amdgpu-pro amdgpu-pro amdgpu-pro-dkms amdgpu-pro-lib32 lib32-clinfo-amdgpu-pro clinfo-amdgpu-pro lib32-gst-omx-amdgpu-pro gst-omx-amdgpu-pro lib32-libdrm-amdgpu-pro-amdgpu1 libdrm-amdgpu-pro-amdgpu1 libdrm-amdgpu-pro-dev lib32-libdrm-amdgpu-pro-dev libdrm-amdgpu-pro-radeon1 lib32-libdrm-amdgpu-pro-radeon1 libdrm-amdgpu-pro-utils lib32-libdrm-amdgpu-pro-utils libdrm2-amdgpu-pro lib32-libdrm2-amdgpu-pro libegl1-amdgpu-pro lib32-libegl1-amdgpu-pro lib32-libgbm1-amdgpu-pro libgbm1-amdgpu-pro libgbm1-amdgpu-pro-base libgbm1-amdgpu-pro-dev lib32-libgbm1-amdgpu-pro-dev libgl1-amdgpu-pro-appprofiles libgl1-amdgpu-pro-dri lib32-libgl1-amdgpu-pro-dri libgl1-amdgpu-pro-ext lib32-libgl1-amdgpu-pro-ext lib32-libgl1-amdgpu-pro-glx libgl1-amdgpu-pro-glx lib32-libglamor-amdgpu-pro-dev libglamor-amdgpu-pro-dev lib32-libgles2-amdgpu-pro libgles2-amdgpu-pro libopencl1-amdgpu-pro lib32-libopencl1-amdgpu-pro lib32-libvdpau-amdgpu-pro libvdpau-amdgpu-pro lib32-mesa-amdgpu-pro-omx-drivers mesa-amdgpu-pro-omx-drivers lib32-opencl-amdgpu-pro-icd opencl-amdgpu-pro-icd vulkan-amdgpu-pro lib32-vulkan-amdgpu-pro lib32-xserver-xorg-video-amdgpu-pro xserver-xorg-video-amdgpu-pro lib32-xserver-xorg-video-glamoregl-amdgpu-pro xserver-xorg-video-glamoregl-amdgpu-pro lib32-xserver-xorg-video-modesetting-amdgpu-pro xserver-xorg-video-modesetting-amdgpu-pro)
if [ "$ALL_PACKAGES" = "true" ]; then
	pkgname+=()
fi
pkgver=16.40.348864
pkgrel=1
arch=('x86_64')
url='http://www.amd.com'
license=('custom:AMD')
makedepends=('wget')

DLAGENTS='https::/usr/bin/wget --referer https://support.amd.com/en-us/kb-articles/Pages/AMD-Radeon-GPU-PRO-Linux-Beta-Driver%E2%80%93Release-Notes.aspx -N %u'

source=(https://www2.ati.com/drivers/linux/ubuntu/amdgpu-pro-16.40-348864.tar.xz
	0001-Find-correct-System.map.patch
	0002-Fix-kernel-module-install-location.patch
	0003-Add-Gentoo-as-build-option.patch
	0004-Remove-extra-parameter-from-ttm_bo_reserve-for-4.7.0.patch
	0005-Remove-first-param-from-drm_gem_object_lookup.patch
	0006-Remove-vblank_disable_allowed-assignment.patch
	0007-Fix-__drm_atomic_helper_connector_destroy_state-call.patch
	0008-Change-seq_printf-format-for-64-bit-context.patch
	0009-Fix-vblank-calls.patch
	0010-Fix-crtc_gamma-functions-for-4.8.0.patch
	0011-Fix-drm_atomic_helper_swap_state-for-4.8.0.patch
	0012-Add-extra-flag-to-ttm_bo_move_ttm-for-4.8.0-rc2.patch
	0013-Remove-dependency-on-System.map.patch
	0014-disable-dal-by-default.patch
	0015-remove-acp_resume.patch
	0016-silence-indentation-build-error.patch)
sha256sums=(59d6b1d975164ff45f6e6be5af6bcc061bf9ef6378ac5757bdb4e67840a706b0
	f052bcf4b974bf6169ae1a20a57e90621becbefbca76f7b239b2e649725e6a56
	ced9e98f7e32fc6b43e38bbb70ebd5e054b2ff3454ccadc527ccf3b19f12d7bb
	0bb77f348512ef2ffa990fd74773d5d283e67c139601347bbd287960a65c0717
	c0422a8ddb6827811710486dd43dca00e8393a1f90786659d4c01d721cff1747
	991115e84b16e4547e35d229faf6b0503b0ad70f8cc59edd7ade026f18fe55bc
	ce924e6159b2a94f48c80954f84e8b6d07245ac58732e7e22ff56264b86c6b73
	7c87b5149d307acf75ec72b00018d9b9f4358bfa441fcf890f544e411256391b
	fa125954b927a6c9eb9c41d30c39f4cfd1f076aa9658cc21fc448a6719f4080f
	74545ec5df05cce5dd5168eb6b57f185ccc1b032b62c24f5f3994a8e8b5ba4b3
	1fe0fe0d457cc403eba513101c000eed054bfe36dd5f5773bb0c9a8b02207f7f
	1a7b834fbe7627ab46afc97fb1272d60607aa57ea43f4a9131ad123fc479679d
	31afb42a7fa7d8090ba8c3b76c3201de54fb357305b7c114fef95707db01f5fe
	cd7d745254e80b25fdd101e4c8f6864a5d4942ba0e88b36e797de6b40e8148d2
	a4a41b3a49ccc227c5182ecb1554cdaefc7c35bd23fffd2b21e86674a49f888e
	a7a4b0dc3368bc767557e4631d1fcafb11ac53face5039ca4b349da41016ef35
	f2b3bec8f6c1ec53639e0d71e9285b5ef8c1633989c8e585dd23da5572003f79)


package_lib32-amdgpu-pro () {
	pkgdesc="Meta package to install amdgpu Pro components."
	depends=('lib32-amdgpu-pro-dkms=16.40.348864-1' 'lib32-libdrm-amdgpu-pro-utils=16.40.348864-1' 'lib32-libgbm1-amdgpu-pro=16.40.348864-1' 'lib32-libgl1-amdgpu-pro-appprofiles=16.40.348864-1' 'lib32-libgl1-amdgpu-pro-glx=16.40.348864-1' 'lib32-libgl1-amdgpu-pro-ext=16.40.348864-1' 'lib32-libgl1-amdgpu-pro-dri=16.40.348864-1' 'lib32-libgles2-amdgpu-pro=16.40.348864-1' 'lib32-vulkan-amdgpu-pro=16.40.348864-1' 'lib32-libvdpau-amdgpu-pro=16.40.348864-1' 'lib32-libopencl1-amdgpu-pro=16.40.348864-1' 'lib32-clinfo-amdgpu-pro=16.40.348864-1' 'lib32-opencl-amdgpu-pro-icd=16.40.348864-1' 'lib32-xserver-xorg-video-glamoregl-amdgpu-pro=16.40.348864-1' 'lib32-xserver-xorg-video-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/amdgpu-pro_16.40-348864_i386
	mkdir "${srcdir}"/amdgpu-pro_16.40-348864_i386
	cd "${srcdir}"/amdgpu-pro_16.40-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./amdgpu-pro_16.40-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_amdgpu-pro () {
	pkgdesc="Meta package to install amdgpu Pro components."
	depends=('amdgpu-pro-dkms=16.40.348864-1' 'libdrm-amdgpu-pro-utils=16.40.348864-1' 'libgbm1-amdgpu-pro=16.40.348864-1' 'libgl1-amdgpu-pro-appprofiles=16.40.348864-1' 'libgl1-amdgpu-pro-glx=16.40.348864-1' 'libgl1-amdgpu-pro-ext=16.40.348864-1' 'libgl1-amdgpu-pro-dri=16.40.348864-1' 'libgles2-amdgpu-pro=16.40.348864-1' 'vulkan-amdgpu-pro=16.40.348864-1' 'libvdpau-amdgpu-pro=16.40.348864-1' 'libopencl1-amdgpu-pro=16.40.348864-1' 'clinfo-amdgpu-pro=16.40.348864-1' 'opencl-amdgpu-pro-icd=16.40.348864-1' 'xserver-xorg-video-glamoregl-amdgpu-pro=16.40.348864-1' 'xserver-xorg-video-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/amdgpu-pro_16.40-348864_amd64
	mkdir "${srcdir}"/amdgpu-pro_16.40-348864_amd64
	cd "${srcdir}"/amdgpu-pro_16.40-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./amdgpu-pro_16.40-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_amdgpu-pro-dkms () {
	pkgdesc="amdgpu-pro driver in DKMS format."
	depends=('dkms>=1.95')
	arch=('any')

	rm -Rf "${srcdir}"/amdgpu-pro-dkms_16.40-348864_all
	mkdir "${srcdir}"/amdgpu-pro-dkms_16.40-348864_all
	cd "${srcdir}"/amdgpu-pro-dkms_16.40-348864_all
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./amdgpu-pro-dkms_16.40-348864_all.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
	(cd ${pkgdir}/usr/src/amdgpu-pro-16.40-348864;
		echo applying 0001-Find-correct-System.map.patch
		patch -p1 -i "${srcdir}/0001-Find-correct-System.map.patch";
		echo applying 0002-Fix-kernel-module-install-location.patch
		patch -p1 -i "${srcdir}/0002-Fix-kernel-module-install-location.patch";
		echo applying 0003-Add-Gentoo-as-build-option.patch
		patch -p1 -i "${srcdir}/0003-Add-Gentoo-as-build-option.patch";
		echo applying 0004-Remove-extra-parameter-from-ttm_bo_reserve-for-4.7.0.patch
		patch -p1 -i "${srcdir}/0004-Remove-extra-parameter-from-ttm_bo_reserve-for-4.7.0.patch";
		echo applying 0005-Remove-first-param-from-drm_gem_object_lookup.patch
		patch -p1 -i "${srcdir}/0005-Remove-first-param-from-drm_gem_object_lookup.patch";
		echo applying 0006-Remove-vblank_disable_allowed-assignment.patch
		patch -p1 -i "${srcdir}/0006-Remove-vblank_disable_allowed-assignment.patch";
		echo applying 0007-Fix-__drm_atomic_helper_connector_destroy_state-call.patch
		patch -p1 -i "${srcdir}/0007-Fix-__drm_atomic_helper_connector_destroy_state-call.patch";
		echo applying 0008-Change-seq_printf-format-for-64-bit-context.patch
		patch -p1 -i "${srcdir}/0008-Change-seq_printf-format-for-64-bit-context.patch";
		echo applying 0009-Fix-vblank-calls.patch
		patch -p1 -i "${srcdir}/0009-Fix-vblank-calls.patch";
		echo applying 0010-Fix-crtc_gamma-functions-for-4.8.0.patch
		patch -p1 -i "${srcdir}/0010-Fix-crtc_gamma-functions-for-4.8.0.patch";
		echo applying 0011-Fix-drm_atomic_helper_swap_state-for-4.8.0.patch
		patch -p1 -i "${srcdir}/0011-Fix-drm_atomic_helper_swap_state-for-4.8.0.patch";
		echo applying 0012-Add-extra-flag-to-ttm_bo_move_ttm-for-4.8.0-rc2.patch
		patch -p1 -i "${srcdir}/0012-Add-extra-flag-to-ttm_bo_move_ttm-for-4.8.0-rc2.patch";
		echo applying 0013-Remove-dependency-on-System.map.patch
		patch -p1 -i "${srcdir}/0013-Remove-dependency-on-System.map.patch";
		echo applying 0014-disable-dal-by-default.patch
		patch -p1 -i "${srcdir}/0014-disable-dal-by-default.patch";
		echo applying 0015-remove-acp_resume.patch
		patch -p1 -i "${srcdir}/0015-remove-acp_resume.patch";
		echo applying 0016-silence-indentation-build-error.patch
		patch -p1 -i "${srcdir}/0016-silence-indentation-build-error.patch")

}


package_amdgpu-pro-lib32 () {
	pkgdesc="Meta package to support i386 runtime on amd64 architecture"
	depends=('libdrm-amdgpu-pro-amdgpu1:i386' 'libgbm1-amdgpu-pro:i386' 'libgl1-amdgpu-pro-glx:i386' 'libgl1-amdgpu-pro-dri:i386' 'libgles2-amdgpu-pro:i386' 'vulkan-amdgpu-pro:i386' 'libvdpau-amdgpu-pro:i386' 'libopencl1-amdgpu-pro:i386' 'opencl-amdgpu-pro-icd:i386')
	arch=('x86_64')

	rm -Rf "${srcdir}"/amdgpu-pro-lib32_16.40-348864_amd64
	mkdir "${srcdir}"/amdgpu-pro-lib32_16.40-348864_amd64
	cd "${srcdir}"/amdgpu-pro-lib32_16.40-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./amdgpu-pro-lib32_16.40-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_lib32-clinfo-amdgpu-pro () {
	pkgdesc="AMD OpenCL info utility"
	depends=('lib32-libopencl1-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/clinfo-amdgpu-pro_16.40-348864_i386
	mkdir "${srcdir}"/clinfo-amdgpu-pro_16.40-348864_i386
	cd "${srcdir}"/clinfo-amdgpu-pro_16.40-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./clinfo-amdgpu-pro_16.40-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_clinfo-amdgpu-pro () {
	pkgdesc="AMD OpenCL info utility"
	depends=('libopencl1-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/clinfo-amdgpu-pro_16.40-348864_amd64
	mkdir "${srcdir}"/clinfo-amdgpu-pro_16.40-348864_amd64
	cd "${srcdir}"/clinfo-amdgpu-pro_16.40-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./clinfo-amdgpu-pro_16.40-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_lib32-gst-omx-amdgpu-pro () {
	pkgdesc="GStreamer OpenMAX plugins"
	depends=('lib32-libglib2.0-0>=2.37.3' 'lib32-libgstreamer-plugins-base1.0-0>=1.6.0' 'lib32-libgstreamer1.0-0>=1.0.0' 'lib32-libomxil-bellagio0')
	arch=('x86_64')

	rm -Rf "${srcdir}"/gst-omx-amdgpu-pro_1.0.0.1-348864_i386
	mkdir "${srcdir}"/gst-omx-amdgpu-pro_1.0.0.1-348864_i386
	cd "${srcdir}"/gst-omx-amdgpu-pro_1.0.0.1-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./gst-omx-amdgpu-pro_1.0.0.1-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_gst-omx-amdgpu-pro () {
	pkgdesc="GStreamer OpenMAX plugins"
	depends=('libglib2.0-0>=2.37.3' 'libgstreamer-plugins-base1.0-0>=1.6.0' 'libgstreamer1.0-0>=1.0.0' 'libomxil-bellagio0')
	arch=('x86_64')

	rm -Rf "${srcdir}"/gst-omx-amdgpu-pro_1.0.0.1-348864_amd64
	mkdir "${srcdir}"/gst-omx-amdgpu-pro_1.0.0.1-348864_amd64
	cd "${srcdir}"/gst-omx-amdgpu-pro_1.0.0.1-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./gst-omx-amdgpu-pro_1.0.0.1-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_lib32-libdrm-amdgpu-pro-amdgpu1 () {
	pkgdesc="Userspace interface to amdgpu-specific kernel DRM services -- runtime"
	depends=('lib32-libdrm2-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libdrm-amdgpu-pro-amdgpu1_1:2.4.66-348864_i386
	mkdir "${srcdir}"/libdrm-amdgpu-pro-amdgpu1_1:2.4.66-348864_i386
	cd "${srcdir}"/libdrm-amdgpu-pro-amdgpu1_1:2.4.66-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libdrm-amdgpu-pro-amdgpu1_2.4.66-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_libdrm-amdgpu-pro-amdgpu1 () {
	pkgdesc="Userspace interface to amdgpu-specific kernel DRM services -- runtime"
	depends=('libdrm2-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libdrm-amdgpu-pro-amdgpu1_1:2.4.66-348864_amd64
	mkdir "${srcdir}"/libdrm-amdgpu-pro-amdgpu1_1:2.4.66-348864_amd64
	cd "${srcdir}"/libdrm-amdgpu-pro-amdgpu1_1:2.4.66-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libdrm-amdgpu-pro-amdgpu1_2.4.66-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_libdrm-amdgpu-pro-dev () {
	pkgdesc="Userspace interface to kernel DRM services -- development files"
	depends=('libdrm2-amdgpu-pro=16.40.348864-1' 'libdrm-amdgpu-pro-amdgpu1=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libdrm-amdgpu-pro-dev_1:2.4.66-348864_amd64
	mkdir "${srcdir}"/libdrm-amdgpu-pro-dev_1:2.4.66-348864_amd64
	cd "${srcdir}"/libdrm-amdgpu-pro-dev_1:2.4.66-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libdrm-amdgpu-pro-dev_2.4.66-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_lib32-libdrm-amdgpu-pro-dev () {
	pkgdesc="Userspace interface to kernel DRM services -- development files"
	depends=('lib32-libdrm2-amdgpu-pro=16.40.348864-1' 'lib32-libdrm-amdgpu-pro-amdgpu1=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libdrm-amdgpu-pro-dev_1:2.4.66-348864_i386
	mkdir "${srcdir}"/libdrm-amdgpu-pro-dev_1:2.4.66-348864_i386
	cd "${srcdir}"/libdrm-amdgpu-pro-dev_1:2.4.66-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libdrm-amdgpu-pro-dev_2.4.66-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_libdrm-amdgpu-pro-radeon1 () {
	pkgdesc="Userspace interface to radeon-specific kernel DRM services -- runtime"
	depends=('libdrm2-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libdrm-amdgpu-pro-radeon1_1:2.4.66-348864_amd64
	mkdir "${srcdir}"/libdrm-amdgpu-pro-radeon1_1:2.4.66-348864_amd64
	cd "${srcdir}"/libdrm-amdgpu-pro-radeon1_1:2.4.66-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libdrm-amdgpu-pro-radeon1_2.4.66-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_lib32-libdrm-amdgpu-pro-radeon1 () {
	pkgdesc="Userspace interface to radeon-specific kernel DRM services -- runtime"
	depends=('lib32-libdrm2-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libdrm-amdgpu-pro-radeon1_1:2.4.66-348864_i386
	mkdir "${srcdir}"/libdrm-amdgpu-pro-radeon1_1:2.4.66-348864_i386
	cd "${srcdir}"/libdrm-amdgpu-pro-radeon1_1:2.4.66-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libdrm-amdgpu-pro-radeon1_2.4.66-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_libdrm-amdgpu-pro-utils () {
	pkgdesc="Utility programs for the kernel DRM interface."
	depends=('libdrm2-amdgpu-pro=16.40.348864-1' 'libdrm-amdgpu-pro-amdgpu1=16.40.348864-1' 'cunit')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libdrm-amdgpu-pro-utils_1:2.4.66-348864_amd64
	mkdir "${srcdir}"/libdrm-amdgpu-pro-utils_1:2.4.66-348864_amd64
	cd "${srcdir}"/libdrm-amdgpu-pro-utils_1:2.4.66-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libdrm-amdgpu-pro-utils_2.4.66-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_lib32-libdrm-amdgpu-pro-utils () {
	pkgdesc="Utility programs for the kernel DRM interface."
	depends=('lib32-libdrm2-amdgpu-pro=16.40.348864-1' 'lib32-libdrm-amdgpu-pro-amdgpu1=16.40.348864-1' 'lib32-cunit')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libdrm-amdgpu-pro-utils_1:2.4.66-348864_i386
	mkdir "${srcdir}"/libdrm-amdgpu-pro-utils_1:2.4.66-348864_i386
	cd "${srcdir}"/libdrm-amdgpu-pro-utils_1:2.4.66-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libdrm-amdgpu-pro-utils_2.4.66-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_libdrm2-amdgpu-pro () {
	pkgdesc="Userspace interface to kernel DRM services -- runtime"
	depends=()
	arch=('x86_64')

	rm -Rf "${srcdir}"/libdrm2-amdgpu-pro_1:2.4.66-348864_amd64
	mkdir "${srcdir}"/libdrm2-amdgpu-pro_1:2.4.66-348864_amd64
	cd "${srcdir}"/libdrm2-amdgpu-pro_1:2.4.66-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libdrm2-amdgpu-pro_2.4.66-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi

	mv ${pkgdir}/lib ${pkgdir}/usr/

}


package_lib32-libdrm2-amdgpu-pro () {
	pkgdesc="Userspace interface to kernel DRM services -- runtime"
	depends=()
	arch=('x86_64')

	rm -Rf "${srcdir}"/libdrm2-amdgpu-pro_1:2.4.66-348864_i386
	mkdir "${srcdir}"/libdrm2-amdgpu-pro_1:2.4.66-348864_i386
	cd "${srcdir}"/libdrm2-amdgpu-pro_1:2.4.66-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libdrm2-amdgpu-pro_2.4.66-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_libegl1-amdgpu-pro () {
	pkgdesc="implementation of the EGL API -- runtime"
	depends=()
	arch=('x86_64')

	rm -Rf "${srcdir}"/libegl1-amdgpu-pro_16.40-348864_amd64
	mkdir "${srcdir}"/libegl1-amdgpu-pro_16.40-348864_amd64
	cd "${srcdir}"/libegl1-amdgpu-pro_16.40-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libegl1-amdgpu-pro_16.40-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_lib32-libegl1-amdgpu-pro () {
	pkgdesc="implementation of the EGL API -- runtime"
	depends=()
	arch=('x86_64')

	rm -Rf "${srcdir}"/libegl1-amdgpu-pro_16.40-348864_i386
	mkdir "${srcdir}"/libegl1-amdgpu-pro_16.40-348864_i386
	cd "${srcdir}"/libegl1-amdgpu-pro_16.40-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libegl1-amdgpu-pro_16.40-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_lib32-libgbm1-amdgpu-pro () {
	pkgdesc="Generic buffer management API -- runtime"
	depends=('lib32-libdrm-amdgpu-pro-amdgpu1=16.40.348864-1' 'lib32-libgbm1-amdgpu-pro-base=16.40.348864-1' 'lib32-libdrm2-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libgbm1-amdgpu-pro_16.40-348864_i386
	mkdir "${srcdir}"/libgbm1-amdgpu-pro_16.40-348864_i386
	cd "${srcdir}"/libgbm1-amdgpu-pro_16.40-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libgbm1-amdgpu-pro_16.40-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_libgbm1-amdgpu-pro () {
	pkgdesc="Generic buffer management API -- runtime"
	depends=('libdrm-amdgpu-pro-amdgpu1=16.40.348864-1' 'libgbm1-amdgpu-pro-base=16.40.348864-1' 'libdrm2-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libgbm1-amdgpu-pro_16.40-348864_amd64
	mkdir "${srcdir}"/libgbm1-amdgpu-pro_16.40-348864_amd64
	cd "${srcdir}"/libgbm1-amdgpu-pro_16.40-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libgbm1-amdgpu-pro_16.40-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_libgbm1-amdgpu-pro-base () {
	pkgdesc="Generic buffer management API -- configuration files"
	depends=()
	arch=('any')

	rm -Rf "${srcdir}"/libgbm1-amdgpu-pro-base_16.40-348864_all
	mkdir "${srcdir}"/libgbm1-amdgpu-pro-base_16.40-348864_all
	cd "${srcdir}"/libgbm1-amdgpu-pro-base_16.40-348864_all
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libgbm1-amdgpu-pro-base_16.40-348864_all.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_libgbm1-amdgpu-pro-dev () {
	pkgdesc="Generic buffer management API -- development files"
	depends=('libgbm1-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libgbm1-amdgpu-pro-dev_16.40-348864_amd64
	mkdir "${srcdir}"/libgbm1-amdgpu-pro-dev_16.40-348864_amd64
	cd "${srcdir}"/libgbm1-amdgpu-pro-dev_16.40-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libgbm1-amdgpu-pro-dev_16.40-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_lib32-libgbm1-amdgpu-pro-dev () {
	pkgdesc="Generic buffer management API -- development files"
	depends=('lib32-libgbm1-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libgbm1-amdgpu-pro-dev_16.40-348864_i386
	mkdir "${srcdir}"/libgbm1-amdgpu-pro-dev_16.40-348864_i386
	cd "${srcdir}"/libgbm1-amdgpu-pro-dev_16.40-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libgbm1-amdgpu-pro-dev_16.40-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_libgl1-amdgpu-pro-appprofiles () {
	pkgdesc="AMD OpenGL profiles configuration"
	depends=()
	arch=('any')

	rm -Rf "${srcdir}"/libgl1-amdgpu-pro-appprofiles_16.40-348864_all
	mkdir "${srcdir}"/libgl1-amdgpu-pro-appprofiles_16.40-348864_all
	cd "${srcdir}"/libgl1-amdgpu-pro-appprofiles_16.40-348864_all
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libgl1-amdgpu-pro-appprofiles_16.40-348864_all.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_libgl1-amdgpu-pro-dri () {
	pkgdesc="implementation of the OpenGL API -- DRI modules"
	depends=('libx11' 'libxext')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libgl1-amdgpu-pro-dri_16.40-348864_amd64
	mkdir "${srcdir}"/libgl1-amdgpu-pro-dri_16.40-348864_amd64
	cd "${srcdir}"/libgl1-amdgpu-pro-dri_16.40-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libgl1-amdgpu-pro-dri_16.40-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_lib32-libgl1-amdgpu-pro-dri () {
	pkgdesc="implementation of the OpenGL API -- DRI modules"
	depends=('lib32-libx11' 'lib32-libxext')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libgl1-amdgpu-pro-dri_16.40-348864_i386
	mkdir "${srcdir}"/libgl1-amdgpu-pro-dri_16.40-348864_i386
	cd "${srcdir}"/libgl1-amdgpu-pro-dri_16.40-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libgl1-amdgpu-pro-dri_16.40-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_libgl1-amdgpu-pro-ext () {
	pkgdesc="xorg GLX exetnsion"
	depends=('libdrm2-amdgpu-pro=16.40.348864-1' 'libgl1-amdgpu-pro-glx=16.40.348864-1' 'libx11' 'libxcb' 'libxdamage>=1.1' 'libxext' 'libxfixes' 'libxxf86vm')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libgl1-amdgpu-pro-ext_16.40-348864_amd64
	mkdir "${srcdir}"/libgl1-amdgpu-pro-ext_16.40-348864_amd64
	cd "${srcdir}"/libgl1-amdgpu-pro-ext_16.40-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libgl1-amdgpu-pro-ext_16.40-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_lib32-libgl1-amdgpu-pro-ext () {
	pkgdesc="xorg GLX exetnsion"
	depends=('lib32-libdrm2-amdgpu-pro=16.40.348864-1' 'lib32-libgl1-amdgpu-pro-glx=16.40.348864-1' 'lib32-libx11' 'lib32-libxcb' 'lib32-libxdamage>=1.1' 'lib32-libxext' 'lib32-libxfixes' 'lib32-libxxf86vm')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libgl1-amdgpu-pro-ext_16.40-348864_i386
	mkdir "${srcdir}"/libgl1-amdgpu-pro-ext_16.40-348864_i386
	cd "${srcdir}"/libgl1-amdgpu-pro-ext_16.40-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libgl1-amdgpu-pro-ext_16.40-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_lib32-libgl1-amdgpu-pro-glx () {
	pkgdesc="implementation of the OpenGL API -- GLX runtime"
	depends=('lib32-libdrm2-amdgpu-pro=16.40.348864-1' 'lib32-libx11>=1.4.99.1' 'lib32-libxcb>=1.8' 'lib32-libxcb' 'lib32-libxcb>=1.9.2' 'lib32-libxdamage>=1.1' 'lib32-libxext' 'lib32-libxfixes' 'lib32-libxshmfence' 'lib32-libxxf86vm')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libgl1-amdgpu-pro-glx_16.40-348864_i386
	mkdir "${srcdir}"/libgl1-amdgpu-pro-glx_16.40-348864_i386
	cd "${srcdir}"/libgl1-amdgpu-pro-glx_16.40-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libgl1-amdgpu-pro-glx_16.40-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi

	provides=('lib32-libgl')
	conflicts=('lib32-libgl')

	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_libgl1-amdgpu-pro-glx () {
	pkgdesc="implementation of the OpenGL API -- GLX runtime"
	depends=('libdrm2-amdgpu-pro=16.40.348864-1' 'libx11>=1.4.99.1' 'libxcb>=1.8' 'libxcb' 'libxcb>=1.9.2' 'libxdamage>=1.1' 'libxext' 'libxfixes' 'libxshmfence' 'libxxf86vm')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libgl1-amdgpu-pro-glx_16.40-348864_amd64
	mkdir "${srcdir}"/libgl1-amdgpu-pro-glx_16.40-348864_amd64
	cd "${srcdir}"/libgl1-amdgpu-pro-glx_16.40-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libgl1-amdgpu-pro-glx_16.40-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi

	provides=('libgl')
	conflicts=('libgl')

}


package_lib32-libglamor-amdgpu-pro-dev () {
	pkgdesc="shared graphics acceleration library based on OpenGL -- development files"
	depends=('lib32-xserver-xorg-video-glamoregl-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libglamor-amdgpu-pro-dev_1.18.3-348864_i386
	mkdir "${srcdir}"/libglamor-amdgpu-pro-dev_1.18.3-348864_i386
	cd "${srcdir}"/libglamor-amdgpu-pro-dev_1.18.3-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libglamor-amdgpu-pro-dev_1.18.3-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_libglamor-amdgpu-pro-dev () {
	pkgdesc="shared graphics acceleration library based on OpenGL -- development files"
	depends=('xserver-xorg-video-glamoregl-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libglamor-amdgpu-pro-dev_1.18.3-348864_amd64
	mkdir "${srcdir}"/libglamor-amdgpu-pro-dev_1.18.3-348864_amd64
	cd "${srcdir}"/libglamor-amdgpu-pro-dev_1.18.3-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libglamor-amdgpu-pro-dev_1.18.3-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_lib32-libgles2-amdgpu-pro () {
	pkgdesc="implementation of the OpenGL|ES 2.x API -- runtime"
	depends=('lib32-libegl1-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libgles2-amdgpu-pro_16.40-348864_i386
	mkdir "${srcdir}"/libgles2-amdgpu-pro_16.40-348864_i386
	cd "${srcdir}"/libgles2-amdgpu-pro_16.40-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libgles2-amdgpu-pro_16.40-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_libgles2-amdgpu-pro () {
	pkgdesc="implementation of the OpenGL|ES 2.x API -- runtime"
	depends=('libegl1-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libgles2-amdgpu-pro_16.40-348864_amd64
	mkdir "${srcdir}"/libgles2-amdgpu-pro_16.40-348864_amd64
	cd "${srcdir}"/libgles2-amdgpu-pro_16.40-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libgles2-amdgpu-pro_16.40-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_libopencl1-amdgpu-pro () {
	pkgdesc="AMD OpenCL ICD Loader library"
	depends=()
	arch=('x86_64')

	rm -Rf "${srcdir}"/libopencl1-amdgpu-pro_16.40-348864_amd64
	mkdir "${srcdir}"/libopencl1-amdgpu-pro_16.40-348864_amd64
	cd "${srcdir}"/libopencl1-amdgpu-pro_16.40-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libopencl1-amdgpu-pro_16.40-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi

	provides=(libcl)
	conflicts=(libcl)

}


package_lib32-libopencl1-amdgpu-pro () {
	pkgdesc="AMD OpenCL ICD Loader library"
	depends=()
	arch=('x86_64')

	rm -Rf "${srcdir}"/libopencl1-amdgpu-pro_16.40-348864_i386
	mkdir "${srcdir}"/libopencl1-amdgpu-pro_16.40-348864_i386
	cd "${srcdir}"/libopencl1-amdgpu-pro_16.40-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libopencl1-amdgpu-pro_16.40-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi

	provides=(lib32-libcl)
	conflicts=(lib32-libcl)

	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_lib32-libvdpau-amdgpu-pro () {
	pkgdesc="AMDGPU Pro VDPAU driver"
	depends=('lib32-libdrm-amdgpu-pro-amdgpu1=16.40.348864-1' 'lib32-libdrm2-amdgpu-pro=16.40.348864-1' 'lib32-openssl>=1.0.0' 'lib32-libtinfo>=6' 'lib32-libxcb>=1.8' 'lib32-libxcb' 'lib32-zlib>=1.2.0' 'lib32-libvdpau>=1.1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libvdpau-amdgpu-pro_1:11.2.2-348864_i386
	mkdir "${srcdir}"/libvdpau-amdgpu-pro_1:11.2.2-348864_i386
	cd "${srcdir}"/libvdpau-amdgpu-pro_1:11.2.2-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libvdpau-amdgpu-pro_11.2.2-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_libvdpau-amdgpu-pro () {
	pkgdesc="AMDGPU Pro VDPAU driver"
	depends=('libdrm-amdgpu-pro-amdgpu1=16.40.348864-1' 'libdrm2-amdgpu-pro=16.40.348864-1' 'openssl>=1.0.0' 'libtinfo>=6' 'libxcb>=1.8' 'libxcb' 'zlib>=1.2.0' 'libvdpau>=1.1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/libvdpau-amdgpu-pro_1:11.2.2-348864_amd64
	mkdir "${srcdir}"/libvdpau-amdgpu-pro_1:11.2.2-348864_amd64
	cd "${srcdir}"/libvdpau-amdgpu-pro_1:11.2.2-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./libvdpau-amdgpu-pro_11.2.2-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_lib32-mesa-amdgpu-pro-omx-drivers () {
	pkgdesc="Mesa OpenMAX video drivers"
	depends=('lib32-libdrm-amdgpu-pro-amdgpu1=16.40.348864-1' 'lib32-libdrm2-amdgpu-pro=16.40.348864-1' 'lib32-libomxil-bellagio0' 'lib32-openssl>=1.0.0' 'lib32-libtinfo>=6' 'lib32-libx11' 'lib32-libxcb>=1.8' 'lib32-libxcb' 'lib32-zlib>=1.2.0')
	arch=('x86_64')

	rm -Rf "${srcdir}"/mesa-amdgpu-pro-omx-drivers_1:11.2.2-348864_i386
	mkdir "${srcdir}"/mesa-amdgpu-pro-omx-drivers_1:11.2.2-348864_i386
	cd "${srcdir}"/mesa-amdgpu-pro-omx-drivers_1:11.2.2-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./mesa-amdgpu-pro-omx-drivers_11.2.2-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_mesa-amdgpu-pro-omx-drivers () {
	pkgdesc="Mesa OpenMAX video drivers"
	depends=('libdrm-amdgpu-pro-amdgpu1=16.40.348864-1' 'libdrm2-amdgpu-pro=16.40.348864-1' 'libomxil-bellagio0' 'openssl>=1.0.0' 'libtinfo>=6' 'libx11' 'libxcb>=1.8' 'libxcb' 'zlib>=1.2.0')
	arch=('x86_64')

	rm -Rf "${srcdir}"/mesa-amdgpu-pro-omx-drivers_1:11.2.2-348864_amd64
	mkdir "${srcdir}"/mesa-amdgpu-pro-omx-drivers_1:11.2.2-348864_amd64
	cd "${srcdir}"/mesa-amdgpu-pro-omx-drivers_1:11.2.2-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./mesa-amdgpu-pro-omx-drivers_11.2.2-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_lib32-opencl-amdgpu-pro-icd () {
	pkgdesc="non-free AMD OpenCL ICD Loaders"
	depends=()
	arch=('x86_64')

	rm -Rf "${srcdir}"/opencl-amdgpu-pro-icd_16.40-348864_i386
	mkdir "${srcdir}"/opencl-amdgpu-pro-icd_16.40-348864_i386
	cd "${srcdir}"/opencl-amdgpu-pro-icd_16.40-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./opencl-amdgpu-pro-icd_16.40-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_opencl-amdgpu-pro-icd () {
	pkgdesc="non-free AMD OpenCL ICD Loaders"
	depends=()
	arch=('x86_64')

	rm -Rf "${srcdir}"/opencl-amdgpu-pro-icd_16.40-348864_amd64
	mkdir "${srcdir}"/opencl-amdgpu-pro-icd_16.40-348864_amd64
	cd "${srcdir}"/opencl-amdgpu-pro-icd_16.40-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./opencl-amdgpu-pro-icd_16.40-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_vulkan-amdgpu-pro () {
	pkgdesc="AMDGPU Pro Vulkan driver"
	depends=('libdrm-amdgpu-pro-amdgpu1=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/vulkan-amdgpu-pro_16.40-348864_amd64
	mkdir "${srcdir}"/vulkan-amdgpu-pro_16.40-348864_amd64
	cd "${srcdir}"/vulkan-amdgpu-pro_16.40-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./vulkan-amdgpu-pro_16.40-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_lib32-vulkan-amdgpu-pro () {
	pkgdesc="AMDGPU Pro Vulkan driver"
	depends=('lib32-libdrm-amdgpu-pro-amdgpu1=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/vulkan-amdgpu-pro_16.40-348864_i386
	mkdir "${srcdir}"/vulkan-amdgpu-pro_16.40-348864_i386
	cd "${srcdir}"/vulkan-amdgpu-pro_16.40-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./vulkan-amdgpu-pro_16.40-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_lib32-xserver-xorg-video-amdgpu-pro () {
	pkgdesc="X.Org X server -- AMD/ATI Radeon display driver"
	depends=('lib32-libdrm-amdgpu-pro-amdgpu1=16.40.348864-1' 'lib32-libgbm1-amdgpu-pro=16.40.348864-1' 'lib32-libsystemd>=183')
	arch=('x86_64')

	rm -Rf "${srcdir}"/xserver-xorg-video-amdgpu-pro_1:1.1.99-348864_i386
	mkdir "${srcdir}"/xserver-xorg-video-amdgpu-pro_1:1.1.99-348864_i386
	cd "${srcdir}"/xserver-xorg-video-amdgpu-pro_1:1.1.99-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./xserver-xorg-video-amdgpu-pro_1.1.99-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_xserver-xorg-video-amdgpu-pro () {
	pkgdesc="X.Org X server -- AMD/ATI Radeon display driver"
	depends=('libdrm-amdgpu-pro-amdgpu1=16.40.348864-1' 'libgbm1-amdgpu-pro=16.40.348864-1' 'libsystemd>=183')
	arch=('x86_64')

	rm -Rf "${srcdir}"/xserver-xorg-video-amdgpu-pro_1:1.1.99-348864_amd64
	mkdir "${srcdir}"/xserver-xorg-video-amdgpu-pro_1:1.1.99-348864_amd64
	cd "${srcdir}"/xserver-xorg-video-amdgpu-pro_1:1.1.99-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./xserver-xorg-video-amdgpu-pro_1.1.99-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi

	conflicts=('xf86-video-amdgpu')
	# This is needed because libglx.so has a hardcoded DRI_DRIVER_PATH
	mkdir -p ${pkgdir}/usr/lib/x86_64-linux-gnu
	ln -s /usr/lib/dri ${pkgdir}/usr/lib/x86_64-linux-gnu/dri

}


package_lib32-xserver-xorg-video-glamoregl-amdgpu-pro () {
	pkgdesc="X.Org X server -- graphics acceleration module based on OpenGL"
	depends=('lib32-libdrm2-amdgpu-pro=16.40.348864-1' 'lib32-libepoxy>=1.0' 'lib32-libgbm1-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/xserver-xorg-video-glamoregl-amdgpu-pro_1.18.3-348864_i386
	mkdir "${srcdir}"/xserver-xorg-video-glamoregl-amdgpu-pro_1.18.3-348864_i386
	cd "${srcdir}"/xserver-xorg-video-glamoregl-amdgpu-pro_1.18.3-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./xserver-xorg-video-glamoregl-amdgpu-pro_1.18.3-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_xserver-xorg-video-glamoregl-amdgpu-pro () {
	pkgdesc="X.Org X server -- graphics acceleration module based on OpenGL"
	depends=('libdrm2-amdgpu-pro=16.40.348864-1' 'libepoxy>=1.0' 'libgbm1-amdgpu-pro=16.40.348864-1')
	arch=('x86_64')

	rm -Rf "${srcdir}"/xserver-xorg-video-glamoregl-amdgpu-pro_1.18.3-348864_amd64
	mkdir "${srcdir}"/xserver-xorg-video-glamoregl-amdgpu-pro_1.18.3-348864_amd64
	cd "${srcdir}"/xserver-xorg-video-glamoregl-amdgpu-pro_1.18.3-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./xserver-xorg-video-glamoregl-amdgpu-pro_1.18.3-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}


package_lib32-xserver-xorg-video-modesetting-amdgpu-pro () {
	pkgdesc="XServer modules for amdgpu-pro This package contains modesetting_drv.so"
	depends=('lib32-libsystemd>=183')
	arch=('x86_64')

	rm -Rf "${srcdir}"/xserver-xorg-video-modesetting-amdgpu-pro_1.18.3-348864_i386
	mkdir "${srcdir}"/xserver-xorg-video-modesetting-amdgpu-pro_1.18.3-348864_i386
	cd "${srcdir}"/xserver-xorg-video-modesetting-amdgpu-pro_1.18.3-348864_i386
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./xserver-xorg-video-modesetting-amdgpu-pro_1.18.3-348864_i386.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/i386-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib32
		mv "${pkgdir}"/usr/lib/i386-linux-gnu/* "${pkgdir}"/usr/lib32
		rmdir "${pkgdir}"/usr/lib/i386-linux-gnu
	fi
	rm -Rf ${pkgdir}/usr/share/doc ${pkgdir}/usr/include
}


package_xserver-xorg-video-modesetting-amdgpu-pro () {
	pkgdesc="XServer modules for amdgpu-pro This package contains modesetting_drv.so"
	depends=('libsystemd>=183')
	arch=('x86_64')

	rm -Rf "${srcdir}"/xserver-xorg-video-modesetting-amdgpu-pro_1.18.3-348864_amd64
	mkdir "${srcdir}"/xserver-xorg-video-modesetting-amdgpu-pro_1.18.3-348864_amd64
	cd "${srcdir}"/xserver-xorg-video-modesetting-amdgpu-pro_1.18.3-348864_amd64
	ar x "${srcdir}"/amdgpu-pro-16.40-348864/./xserver-xorg-video-modesetting-amdgpu-pro_1.18.3-348864_amd64.deb
	tar -C "${pkgdir}" -xf data.tar.xz

	if [ -d "${pkgdir}/usr/lib/x86_64-linux-gnu" ]; then
		mkdir -p "${pkgdir}"/usr/lib
		mv "${pkgdir}"/usr/lib/x86_64-linux-gnu/* "${pkgdir}"/usr/lib
		rmdir "${pkgdir}"/usr/lib/x86_64-linux-gnu
	fi
}

