# Generated with ./gen_replace_deps.sh > replace_deps.py
# for driver version 19.50-967956

replace_deps = {
    'binfmt-support':                  'opera',                  #auto_translated
    'dkms':                            'dkms',                   #auto_translated
    'libc6':                           'glibc',                  #manually_mapped
    'libcunit1':                       'cunit',                  #auto_translated
    'libdrm-radeon1':                  'libdrm',                 #auto_translated
    'libedit2':                        'libedit',                #auto_translated
    'libelf1':                         'libelf',                 #auto_translated
    'libepoxy0':                       'libepoxy',               #auto_translated
    'libexpat1':                       'expat',                  #auto_translated
    'libffi6':                         'libffi',                 #auto_translated
    'libffi-dev':                      'libffi',                 #auto_translated
    'libgcc1':                         None,                     #auto_translated
    'libglib2.0-0':                    'glib2',                  #auto_translated
    'libglide3':                       'glide',                  #auto_translated
    'libgstreamer1.0-0':               'gstreamer',              #auto_translated
    'libgstreamer-plugins-base1.0-0':  'gst-plugins-base-libs',  #auto_translated
    'libmirclient-dev':                'libmirclient-dev',       #could_not_auto_translate
    'libnuma1':                        'numactl',                #auto_translated
    'libomxil-bellagio0':              'libomxil-bellagio',      #auto_translated
    'libpci3':                         None,                     #auto_translated
    'libselinux1':                     'libselinux',             #auto_translated
    'libstdc++6':                      'gcc-libs',               #manually_mapped
    'libtinfo5':                       'ncurses5-compat-libs',   #manually_mapped
    'libtinfo-dev':                    'ncurses',                #manually_mapped
    'libtxc-dxtn0':                    None,                     #manually_mapped
    'libtxc-dxtn-s2tc0':               'libtxc_dxtn',            #manually_mapped
    'libudev0':                        None,                     #manually_mapped
    'libudev1':                        'systemd-libs',           #auto_translated
    'libudev-dev':                     'systemd-libs',           #auto_translated
    'libx11-6':                        'libx11',                 #auto_translated
    'libx11-dev':                      'libx11',                 #auto_translated
    'libx11-xcb1':                     'libx11',                 #auto_translated
    'libx11-xcb-dev':                  'libx11',                 #auto_translated
    'libxcb1':                         'libxcb',                 #auto_translated
    'libxcb-dri2-0':                   'libxcb',                 #auto_translated
    'libxcb-dri2-0-dev':               'libxcb',                 #auto_translated
    'libxcb-dri3-0':                   'libxcb',                 #auto_translated
    'libxcb-dri3-dev':                 'libxcb',                 #auto_translated
    'libxcb-glx0':                     'libxcb',                 #auto_translated
    'libxcb-glx0-dev':                 'libxcb',                 #auto_translated
    'libxcb-present0':                 'libxcb',                 #auto_translated
    'libxcb-present-dev':              'libxcb',                 #auto_translated
    'libxcb-sync1':                    'libxcb',                 #auto_translated
    'libxcb-sync-dev':                 'libxcb',                 #auto_translated
    'libxcb-xfixes0':                  'libxcb',                 #auto_translated
    'libxdamage1':                     'libxdamage',             #auto_translated
    'libxdamage-dev':                  'libxdamage',             #auto_translated
    'libxext6':                        'libxext',                #auto_translated
    'libxext-dev':                     'libxext',                #auto_translated
    'libxfixes3':                      'libxfixes',              #auto_translated
    'libxfixes-dev':                   'libxfixes',              #auto_translated
    'libxml2':                         'libxml2',                #auto_translated
    'libxshmfence1':                   'libxshmfence',           #auto_translated
    'libxshmfence-dev':                'libxshmfence',           #auto_translated
    'libxxf86vm1':                     'libxxf86vm',             #auto_translated
    'libxxf86vm-dev':                  'libxxf86vm',             #auto_translated
    'linux-firmware':                  None,                     #auto_translated
    'x11proto-dri2-dev':               'x11proto-dri2-dev',      #could_not_auto_translate
    'x11proto-gl-dev':                 'x11proto-gl-dev',        #could_not_auto_translate
    'xserver-xorg-hwe-18.04':          None,                     #manually_disabled
    'zlib1g':                          'zlib',                   #auto_translated
    'libva1':                          'libva1',                 #auto_translated
    'libva1-amdgpu':                   'libva1',                 #auto_translated
    'libva2':                          'libva',                  #auto_translated
    'libva2-amdgpu':                   'libva',                  #auto_translated
    'libvdpau1':                       'libvdpau',               #auto_translated
    'libvdpau1-amdgpu':                'libvdpau',               #auto_translated
}
